development:
  adapter: postgresql
  encoding: unicode
  database: shakespeare_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shakespeare_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: shakespeare_production
  pool: 5
  username:
  password:
